name: Release Caller

on:
  workflow_run:
    workflows: ["Main release"]
    types: [completed]

  workflow_dispatch:

# Package and upload the Python package
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3
        with:
          ref: "master"

      # Upgrade pip
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      # Cache dependencies
      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/extras/docs.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install twine
      - name: Install dependencies
        run: python3 -m pip install twine

      # Make docs
      - name: Build sdist and wheels
        run: |
          cd caller
          python3 setup.py bdist_wheel
          python3 setup.py sdist

      # Upload to PyPI
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY_TEXTRACTOR }}
