# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch and changes in folder src-python
name: Test-Pull-Request-PrettyPrinter
on:
  push:
    paths:
      - prettyprinter
  pull_request_target:
    branches: [master]
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch: {}

# Run the tests
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: ./prettyprinter

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Install package locally
      - name: Install package
        run: python -m pip install -e .

      # Install dev dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      # Run tests
      - name: Test
        run: pytest
